<?php
/** @var $block \Smile\Customer\Block\VisitedUrls */
?>
<h2>The Magento DevTeam Visited Urls (first ones)</h2>
<table>
    <tr>
        <th><?php echo __('Customer Id')?></th>
        <th><?php echo __('Visited Url')?></th>
        <th><?php echo __('Active Status')?></th>
        <th><?php echo __('IP')?></th>
    </tr>
    <?php foreach ($block->getFirstMagentoDevsUrls()->getItems() as $item): ?>
    <tr>
        <td><?php echo $item->getCustomerId() ?: 'Not a member of the DevTeam'?></td>
        <td><?php echo $item->getVisitedUrl(); ?></td>
        <td><?php echo $item->getIsAcive() ? 'Enabled' : 'Disabled'; ?></td>
        <td><?php echo $item->getClientIp(); ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<p></p>
<h2>The Magento DevTeam Visited Urls (last ones)</h2>
<table>
    <tr>
        <th><?php echo __('Customer Id')?></th>
        <th><?php echo __('Visited Url')?></th>
        <th><?php echo __('Active Status')?></th>
        <th><?php echo __('Client IP')?></th>
    </tr>
    <?php foreach ($block->getLastMagentoDevUrls()->getItems() as $item): ?>
        <tr>
            <td><?php echo $item->getCustomerId() ?: 'Not a member of the DevTeam'?></td>
            <td><?php echo $item->getVisitedUrl(); ?></td>
            <td><?php echo $item->getIsAcive() ? 'Enabled' : 'Disabled'; ?></td>
            <td><?php echo $item->getClientIp(); ?></td>
        </tr>
    <?php endforeach; ?>
</table>

